import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "سبزلرن | SabzLearn",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/fav.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-screen items-center justify-center p-4">
        {children}
    </div>
 
  );
}